# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='激活码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '保密')], default=0, verbose_name='性别'),
        ),
    ]
