# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170523_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='门店分类')),
            ],
            options={
                'verbose_name': '门店 - 分类',
                'verbose_name_plural': '门店 - 分类',
            },
        ),
        migrations.AddField(
            model_name='stores',
            name='category',
            field=models.ManyToManyField(to='user.StoreCategory', verbose_name='分类'),
        ),
    ]
