# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_stores_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='注目语')),
            ],
            options={
                'verbose_name': '商品 - 注目语',
                'verbose_name_plural': '商品 - 注目语',
            },
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='chindren_num',
            field=models.IntegerField(default=0, verbose_name='小孩人数'),
        ),
        migrations.AddField(
            model_name='food',
            name='words',
            field=models.ManyToManyField(to='user.FoodWord', verbose_name='注目语'),
        ),
    ]
