# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170523_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='images',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Food', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='words',
            field=models.ManyToManyField(blank=True, null=True, to='user.FoodWord', verbose_name='注目语'),
        ),
    ]
