# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170524_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='desk_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.DeskCategory', verbose_name='桌位类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='food',
            name='words',
            field=models.ManyToManyField(blank=True, to='user.FoodWord', verbose_name='注目语'),
        ),
        migrations.AlterField(
            model_name='foodspec',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='价格'),
        ),
    ]
