# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170524_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='sell_period',
        ),
        migrations.RemoveField(
            model_name='sellperiod',
            name='store',
        ),
        migrations.AddField(
            model_name='sellperiod',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Food', verbose_name='商品'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='image_size',
            field=models.IntegerField(choices=[(0, '大'), (1, '中'), (2, '小')], default=1, verbose_name='图片大小'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stores',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
