# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20170524_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='foodspec',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
    ]
