# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_coupon_coupontime_discountcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontime',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='周五'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='周一'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='周六'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='周日'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='周四'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='周二'),
        ),
        migrations.AddField(
            model_name='coupontime',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='周三'),
        ),
    ]
