# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20170530_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullMinusCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='发放张数')),
                ('daily_limit', models.IntegerField(blank=True, null=True, verbose_name='每日每人限额')),
                ('single_limit', models.IntegerField(blank=True, null=True, verbose_name='单人限额')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Coupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name_plural': '优惠券 - 满减优惠券',
                'verbose_name': '优惠券 - 满减优惠券',
            },
        ),
        migrations.CreateModel(
            name='FullMinusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.IntegerField(verbose_name='满')),
                ('coupon_type', models.IntegerField(choices=[(0, '减'), (1, '赠')], verbose_name='促销方式')),
                ('minus', models.IntegerField(verbose_name='减')),
                ('full_minus_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FullMinusCoupon', verbose_name='优惠券')),
                ('gift', models.ManyToManyField(to='user.Food', verbose_name='赠品')),
            ],
            options={
                'verbose_name_plural': '优惠券 - 满减优惠券详情',
                'verbose_name': '优惠券 - 满减优惠券详情',
            },
        ),
    ]
