# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20170531_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullminusdetail',
            name='gift',
            field=models.ManyToManyField(blank=True, to='user.Food', verbose_name='赠品'),
        ),
        migrations.AlterField(
            model_name='fullminusdetail',
            name='minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='减'),
        ),
    ]
