# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20170614_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='cardno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='coupontime',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_time', to='user.Coupon', verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='foodspec',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodspec', to='user.Food', verbose_name='商品'),
        ),
    ]
