# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_couponcode_receive_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='用餐时间')),
                ('status', models.IntegerField(choices=[(0, '用餐中'), (1, '用餐结束')], default=0, verbose_name='用餐状态')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Desk', verbose_name='桌号')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='用餐店铺')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='用餐用户')),
            ],
            options={
                'verbose_name_plural': '用餐',
                'verbose_name': '用餐',
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.IntegerField(choices=[(0, '线下支付'), (1, '银行卡支付'), (2, '会员点支付'), (3, '金币支付')], verbose_name='支付方式')),
                ('money', models.IntegerField(verbose_name='支付金额')),
                ('coupon_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.CouponCode', verbose_name='优惠券')),
            ],
            options={
                'verbose_name_plural': '支付信息',
                'verbose_name': '支付信息',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='food',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='order_comment',
            options={'verbose_name': '订单 - 评价'},
        ),
        migrations.AlterModelOptions(
            name='order_comment_image',
            options={'verbose_name': '订单 - 评价图片'},
        ),
        migrations.AlterModelOptions(
            name='order_food',
            options={'verbose_name': '订单 - 商品', 'verbose_name_plural': '订单 - 商品'},
        ),
        migrations.AlterModelOptions(
            name='order_food_comment',
            options={'verbose_name': '订单 - 商品评价', 'verbose_name_plural': '订单 - 商品评价'},
        ),
        migrations.AlterModelOptions(
            name='order_food_comment_image',
            options={'verbose_name': '订单 - 商品评价图片', 'verbose_name_plural': '订单 - 商品评价图片'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_comment_image',
            name='order_food_comment',
        ),
        migrations.RemoveField(
            model_name='order_food',
            name='is_comment',
        ),
        migrations.AddField(
            model_name='coupon',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_receive',
            field=models.BooleanField(default=True, verbose_name='是否需要领取'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '仅参与'), (2, '已删除')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='订单编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '已评价'), (3, '申请退款'), (4, '已退款'), (5, '退款客服介入中')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='总价'),
        ),
        migrations.AddField(
            model_name='order_comment',
            name='comment',
            field=models.CharField(default=1, max_length=100, verbose_name='评价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_comment',
            name='order_star',
            field=models.IntegerField(default=0, verbose_name='星级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_comment_image',
            name='order_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Order_Comment', verbose_name='订单评价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitecoupon',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='user.FoodCategory', verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_comment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='user.Order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='order_food_comment',
            name='order_food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='user.Order_Food', verbose_name='订单商品'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartDetail',
        ),
        migrations.AddField(
            model_name='payinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_pay', to='user.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_meal', to='user.Meal', verbose_name='用餐'),
            preserve_default=False,
        ),
    ]
