# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20170617_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=50, verbose_name='订单编号'),
        ),
    ]
