# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20170617_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food',
            name='food_spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.FoodSpec', verbose_name='商品规格'),
            preserve_default=False,
        ),
    ]
