# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_meal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food',
            name='tag',
            field=models.ManyToManyField(to='user.Tag', verbose_name='标签'),
        ),
    ]
