# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20170619_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='desk',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
        migrations.AddField(
            model_name='order_food',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
        migrations.AddField(
            model_name='stores',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
    ]
