# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20170620_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='detail_minor',
            field=models.TextField(blank=True, null=True, verbose_name='优惠券详情 - 次'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='coupon_food', to='user.Food', verbose_name='打折商品'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(0, '定额'), (1, '折扣'), (2, '满赠')], default=0, verbose_name='折扣类型'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='gift',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Food', verbose_name='赠品'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='more_gift',
            field=models.IntegerField(blank=True, default=0, verbose_name='满赠个数'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='num',
            field=models.IntegerField(default=0, verbose_name='赠品数量'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='quota',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='定额优惠金额'),
        ),
    ]
