# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_order_food_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='大人')),
                ('chindren_num', models.IntegerField(default=0, verbose_name='小孩人数')),
                ('no_smoking', models.BooleanField(default=False, verbose_name='禁烟')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('desk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.DeskCategory', verbose_name='桌位类型')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '排队',
                'verbose_name_plural': '排队',
            },
        ),
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='排号')),
                ('is_use', models.BooleanField(default=False, verbose_name='是否用餐')),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Queue')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '排队记录',
                'verbose_name_plural': '排队记录',
            },
        ),
        migrations.AlterField(
            model_name='foodspec',
            name='stock',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='库存'),
        ),
    ]
