# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20170622_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='is_queue',
            field=models.BooleanField(default=False, verbose_name='是否排队'),
        ),
        migrations.AddField(
            model_name='stores',
            name='status',
            field=models.IntegerField(choices=[(0, '正常营业'), (1, '休息中'), (2, '停业')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='store_ad',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_ad_img', to='user.Stores'),
        ),
        migrations.AlterField(
            model_name='store_rotation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_rotation', to='user.Stores', verbose_name='门店'),
        ),
    ]
