# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_auto_20170622_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '线上支付'), (1, '线下支付')], default=0, verbose_name='方式'),
        ),
    ]
