# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_payinfo_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food',
            name='status',
            field=models.IntegerField(choices=[(0, '等待支付'), (1, '未制作'), (2, '已做出'), (3, '已上菜')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='payinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '现金支付(未支付)'), (2, '现金支付(已支付)'), (3, '已支付'), (4, '已评价'), (5, '申请退款'), (6, '已退款'), (7, '退款客服介入中')], default=0, verbose_name='状态'),
        ),
    ]
