# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20170623_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='支付时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='用户编号'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, '顾客'), (1, '门店管理员'), (2, '厨师'), (2, '服务员'), (2, '收银员'), (3, '平台管理员')], default=0, verbose_name='用户类型'),
        ),
    ]
