# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20170624_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
