# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_goldlog_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_food',
            name='tag',
            field=models.ManyToManyField(related_name='order_food_tag', to='user.Tag', verbose_name='标签'),
        ),
    ]
