# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20170624_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(0, '上菜太慢'), (1, '不想吃了'), (2, '不好吃'), (3, '吃饱啦'), (4, '服务态度不好'), (5, '不卫生'), (6, '其他')], verbose_name='理由')),
                ('desc', models.TextField(verbose_name='描述')),
                ('status', models.IntegerField(choices=[(0, '已申请'), (1, '门店同意'), (2, '门店拒绝')], default=0, verbose_name='状态')),
                ('refuse_desc', models.TextField(blank=True, null=True, verbose_name='拒绝理由')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order', verbose_name='订单')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='门店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '退款信息',
                'verbose_name_plural': '退款信息',
            },
        ),
    ]
