# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_refundorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorder',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Order_Food', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='num',
            field=models.IntegerField(default=0, verbose_name='商品退货数量'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_cash',
            field=models.IntegerField(default=-1, verbose_name='退款现金'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_gold',
            field=models.IntegerField(default=-1, verbose_name='退款会员点'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_point',
            field=models.IntegerField(default=-1, verbose_name='退款会员点'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='refund_type',
            field=models.IntegerField(choices=[(0, '订单退款'), (1, '商品退款')], default=0, verbose_name='退款类型'),
            preserve_default=False,
        ),
    ]
