# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20170625_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='refund_gold',
            field=models.IntegerField(default=-1, verbose_name='退款金币'),
        ),
    ]
