# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_auto_20170625_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorder',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='refund_order/', verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='refund_order/', verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='refund_order/', verbose_name='图片3'),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='refund_order/', verbose_name='图片4'),
        ),
    ]
