# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_auto_20170626_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='支付编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payinfo',
            name='limit_price',
            field=models.IntegerField(default=0, verbose_name='优惠金额'),
        ),
    ]
