# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0063_auto_20170629_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='订单编号'),
        ),
    ]
