# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_order_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, '顾客'), (1, '门店管理员'), (2, '厨师'), (3, '服务员'), (4, '收银员'), (5, '平台管理员')], default=0, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='storepointlog',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '现金'), (1, '金币'), (2, '退款'), (3, '消费')], default=0, verbose_name='支付方式'),
        ),
    ]
