# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_storepaytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': '门店 - 餐桌', 'verbose_name_plural': '门店 - 餐桌'},
        ),
        migrations.AlterModelOptions(
            name='deskcategory',
            options={'verbose_name': '门店 - 餐桌类别', 'verbose_name_plural': '门店 - 餐桌类别'},
        ),
        migrations.AlterModelOptions(
            name='storepaytype',
            options={'verbose_name': '门店 - 支付方式', 'verbose_name_plural': '门店 - 支付方式'},
        ),
    ]
