# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_auto_20170708_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_food',
            options={'ordering': ('-created',), 'verbose_name': '订单 - 商品', 'verbose_name_plural': '订单 - 商品'},
        ),
    ]
