# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20170708_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='display_background',
            field=models.BooleanField(default=False, verbose_name='只显示背景图片和详情次'),
            preserve_default=False,
        ),
    ]
