# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_auto_20170717_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '现金支付(未支付)'), (2, '现金支付(已支付)'), (3, '已支付'), (4, '已评价'), (5, '申请退款'), (6, '已退款'), (7, '拒绝退款'), (8, '退款客服介入中'), (9, '关闭')], default=0, verbose_name='状态'),
        ),
    ]
