# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0083_coupon_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='receive_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='领取时间'),
            preserve_default=False,
        ),
    ]
