# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0084_auto_20170726_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspec',
            name='in_tax_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='含税价格'),
        ),
        migrations.AddField(
            model_name='foodspec',
            name='in_tax_vip_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='会员含税价格'),
        ),
        migrations.AddField(
            model_name='foodspec',
            name='tax_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='税'),
        ),
        migrations.AddField(
            model_name='foodspec',
            name='vip_tax_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='VIP税'),
        ),
        migrations.AlterField(
            model_name='foodspec',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='不含税价格'),
        ),
        migrations.AlterField(
            model_name='foodspec',
            name='vip_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='会员不含税价格'),
        ),
    ]
