# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0085_auto_20170801_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_food',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='不含税价格'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='vip_price',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='不含税VIP价格'),
        ),
    ]
