# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_abstractuser_basemob_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_img/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='is_basemob',
            field=models.BooleanField(default=False, verbose_name='是否接收环信消息'),
        ),
    ]
