# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0093_usergift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_food',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='是否赠品'),
        ),
        migrations.AddField(
            model_name='usergift',
            name='is_use',
            field=models.BooleanField(default=False, verbose_name='是否使用'),
        ),
        migrations.AddField(
            model_name='usergift',
            name='payinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.PayInfo', verbose_name='支付信息'),
        ),
        migrations.AddField(
            model_name='usergift',
            name='use_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
