# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nuser.proto\"3\n\x0cLoginRequest\x12\x11\n\ttelephone\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"V\n\rLoginResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x14\n\x0crefreshtoken\x18\x04 \x01(\t\";\n\x08UserInfo\x12\x10\n\x08\x66ullname\x18\x01 \x01(\t\x12\x0b\n\x03sex\x18\x02 \x01(\t\x12\x10\n\x08\x62irthday\x18\x03 \x01(\x04\"-\n\x18sendTelephoneCodeRequest\x12\x11\n\ttelephone\x18\x01 \x01(\t\"/\n\x19sendTelephoneCodeResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\"7\n\x14verfTelephoneRequest\x12\x11\n\ttelephone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"+\n\x15verfTelephoneResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\"D\n\x11\x63reateRoleRequest\x12\x10\n\x08\x66ullname\x18\x01 \x01(\t\x12\x10\n\x08\x62irthday\x18\x02 \x01(\t\x12\x0b\n\x03sex\x18\x03 \x01(\t\"J\n\x04Role\x12\x0e\n\x06roleid\x18\x01 \x01(\t\x12\x10\n\x08\x66ullname\x18\x02 \x01(\t\x12\x10\n\x08imgindex\x18\x03 \x01(\t\x12\x0e\n\x06isTemp\x18\x04 \x01(\x08\"_\n\x12\x63reateRoleResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\x12\x0e\n\x06userid\x18\x02 \x01(\t\x12\x10\n\x08\x66ullname\x18\x03 \x01(\t\x12\x13\n\x04role\x18\x04 \x01(\x0b\x32\x05.Role\" \n\x0fgetRolesRequest\x12\r\n\x05token\x18\x01 \x01(\t\"<\n\x10getRolesResponse\x12\x12\n\nstatuscode\x18\x01 \x01(\x05\x12\x14\n\x05roles\x18\x02 \x03(\x0b\x32\x05.Roleb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telephone', full_name='LoginRequest.telephone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=65,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='LoginResponse.statuscode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='LoginResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='LoginResponse.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refreshtoken', full_name='LoginResponse.refreshtoken', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=153,
)


_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fullname', full_name='UserInfo.fullname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='UserInfo.sex', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='UserInfo.birthday', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=214,
)


_SENDTELEPHONECODEREQUEST = _descriptor.Descriptor(
  name='sendTelephoneCodeRequest',
  full_name='sendTelephoneCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telephone', full_name='sendTelephoneCodeRequest.telephone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=261,
)


_SENDTELEPHONECODERESPONSE = _descriptor.Descriptor(
  name='sendTelephoneCodeResponse',
  full_name='sendTelephoneCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='sendTelephoneCodeResponse.statuscode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=310,
)


_VERFTELEPHONEREQUEST = _descriptor.Descriptor(
  name='verfTelephoneRequest',
  full_name='verfTelephoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telephone', full_name='verfTelephoneRequest.telephone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='verfTelephoneRequest.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=367,
)


_VERFTELEPHONERESPONSE = _descriptor.Descriptor(
  name='verfTelephoneResponse',
  full_name='verfTelephoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='verfTelephoneResponse.statuscode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=412,
)


_CREATEROLEREQUEST = _descriptor.Descriptor(
  name='createRoleRequest',
  full_name='createRoleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fullname', full_name='createRoleRequest.fullname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='birthday', full_name='createRoleRequest.birthday', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='createRoleRequest.sex', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=482,
)


_ROLE = _descriptor.Descriptor(
  name='Role',
  full_name='Role',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roleid', full_name='Role.roleid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='Role.fullname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imgindex', full_name='Role.imgindex', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isTemp', full_name='Role.isTemp', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=558,
)


_CREATEROLERESPONSE = _descriptor.Descriptor(
  name='createRoleResponse',
  full_name='createRoleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='createRoleResponse.statuscode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userid', full_name='createRoleResponse.userid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='createRoleResponse.fullname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='role', full_name='createRoleResponse.role', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=655,
)


_GETROLESREQUEST = _descriptor.Descriptor(
  name='getRolesRequest',
  full_name='getRolesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='getRolesRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=689,
)


_GETROLESRESPONSE = _descriptor.Descriptor(
  name='getRolesResponse',
  full_name='getRolesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statuscode', full_name='getRolesResponse.statuscode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roles', full_name='getRolesResponse.roles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=691,
  serialized_end=751,
)

_CREATEROLERESPONSE.fields_by_name['role'].message_type = _ROLE
_GETROLESRESPONSE.fields_by_name['roles'].message_type = _ROLE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['sendTelephoneCodeRequest'] = _SENDTELEPHONECODEREQUEST
DESCRIPTOR.message_types_by_name['sendTelephoneCodeResponse'] = _SENDTELEPHONECODERESPONSE
DESCRIPTOR.message_types_by_name['verfTelephoneRequest'] = _VERFTELEPHONEREQUEST
DESCRIPTOR.message_types_by_name['verfTelephoneResponse'] = _VERFTELEPHONERESPONSE
DESCRIPTOR.message_types_by_name['createRoleRequest'] = _CREATEROLEREQUEST
DESCRIPTOR.message_types_by_name['Role'] = _ROLE
DESCRIPTOR.message_types_by_name['createRoleResponse'] = _CREATEROLERESPONSE
DESCRIPTOR.message_types_by_name['getRolesRequest'] = _GETROLESREQUEST
DESCRIPTOR.message_types_by_name['getRolesResponse'] = _GETROLESRESPONSE

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERINFO,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)

sendTelephoneCodeRequest = _reflection.GeneratedProtocolMessageType('sendTelephoneCodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDTELEPHONECODEREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:sendTelephoneCodeRequest)
  ))
_sym_db.RegisterMessage(sendTelephoneCodeRequest)

sendTelephoneCodeResponse = _reflection.GeneratedProtocolMessageType('sendTelephoneCodeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDTELEPHONECODERESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:sendTelephoneCodeResponse)
  ))
_sym_db.RegisterMessage(sendTelephoneCodeResponse)

verfTelephoneRequest = _reflection.GeneratedProtocolMessageType('verfTelephoneRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERFTELEPHONEREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:verfTelephoneRequest)
  ))
_sym_db.RegisterMessage(verfTelephoneRequest)

verfTelephoneResponse = _reflection.GeneratedProtocolMessageType('verfTelephoneResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERFTELEPHONERESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:verfTelephoneResponse)
  ))
_sym_db.RegisterMessage(verfTelephoneResponse)

createRoleRequest = _reflection.GeneratedProtocolMessageType('createRoleRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROLEREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:createRoleRequest)
  ))
_sym_db.RegisterMessage(createRoleRequest)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), dict(
  DESCRIPTOR = _ROLE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:Role)
  ))
_sym_db.RegisterMessage(Role)

createRoleResponse = _reflection.GeneratedProtocolMessageType('createRoleResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROLERESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:createRoleResponse)
  ))
_sym_db.RegisterMessage(createRoleResponse)

getRolesRequest = _reflection.GeneratedProtocolMessageType('getRolesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETROLESREQUEST,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:getRolesRequest)
  ))
_sym_db.RegisterMessage(getRolesRequest)

getRolesResponse = _reflection.GeneratedProtocolMessageType('getRolesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETROLESRESPONSE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:getRolesResponse)
  ))
_sym_db.RegisterMessage(getRolesResponse)


# @@protoc_insertion_point(module_scope)
