# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170520_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_ad',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store_image',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store_kitchen',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store_lobby',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store_other',
            old_name='Store',
            new_name='store',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址详情'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='full_name_spell',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名拼写'),
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='deskaudio',
            name='desk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Desk', verbose_name='餐桌音频'),
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='image',
            field=models.ImageField(upload_to='food/', verbose_name='商品图片'),
        ),
    ]
