# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170523_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总价')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '订单 - 评价',
                'verbose_name': '订单 - 评价',
            },
        ),
        migrations.CreateModel(
            name='Order_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order', verbose_name='订单')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Comment_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='comment_img/', verbose_name='图片')),
                ('order_food_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order_Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('is_comment', models.BooleanField(default=False, verbose_name='是否评价')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Food', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name_plural': '订单 - 商品评价',
                'verbose_name': '订单 - 商品评价',
            },
        ),
        migrations.CreateModel(
            name='Order_Food_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_star', models.IntegerField(verbose_name='评级')),
                ('comment', models.CharField(max_length=200, verbose_name='评价')),
                ('order_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food', to='user.Order_Food', verbose_name='订单商品')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Food_Comment_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='food_comment_img/', verbose_name='图片')),
                ('order_food_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Order_Food_Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '提交'), (1, '门店接受'), (2, '门店拒绝'), (3, '已取消')], default=0, verbose_name='状态')),
                ('tel', models.CharField(max_length=20, verbose_name='手机号')),
                ('num', models.IntegerField(verbose_name='用餐人数')),
                ('no_smoking', models.BooleanField(default=False, verbose_name='禁烟')),
                ('datetime', models.DateTimeField(verbose_name='用餐时间')),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Desk')),
            ],
            options={
                'verbose_name_plural': '预约',
                'verbose_name': '预约',
            },
        ),
        migrations.CreateModel(
            name='Store_Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '用户收藏夹',
                'verbose_name': '用户收藏夹',
            },
        ),
        migrations.AddField(
            model_name='stores',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stores',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store_favorite',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='store_favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
