# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170523_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='网址'),
        ),
    ]
