# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170524_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='sell_week',
        ),
        migrations.AddField(
            model_name='food',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='周五'),
        ),
        migrations.AddField(
            model_name='food',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='周一'),
        ),
        migrations.AddField(
            model_name='food',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='周六'),
        ),
        migrations.AddField(
            model_name='food',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='周日'),
        ),
        migrations.AddField(
            model_name='food',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='周四'),
        ),
        migrations.AddField(
            model_name='food',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='周二'),
        ),
        migrations.AddField(
            model_name='food',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='周三'),
        ),
    ]
