# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170524_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellperiod',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='user.Food', verbose_name='商品'),
        ),
    ]
