# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20170525_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store_favorite',
            options={'ordering': ['id'], 'verbose_name': '用户收藏夹', 'verbose_name_plural': '用户收藏夹'},
        ),
        migrations.AddField(
            model_name='stores',
            name='in_business',
            field=models.BooleanField(default=False, verbose_name='是否营业'),
        ),
    ]
