# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20170525_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUnReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='门店')),
            ],
            options={
                'verbose_name': '门店 - 停止预约时间段',
                'verbose_name_plural': '门店 - 停止预约时间段',
            },
        ),
    ]
