# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_fullminuscoupon_fullminusdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='发放张数')),
                ('daily_limit', models.IntegerField(blank=True, null=True, verbose_name='每日每人限额')),
                ('single_limit', models.IntegerField(blank=True, null=True, verbose_name='单人限额')),
            ],
            options={
                'verbose_name': '优惠券 - 均一价格',
                'verbose_name_plural': '优惠券 - 均一价格',
            },
        ),
        migrations.CreateModel(
            name='UniteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.IntegerField(verbose_name='选')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('unite_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UniteCoupon', verbose_name='优惠券')),
            ],
            options={
                'verbose_name': '优惠券 - 均一价格详情',
                'verbose_name_plural': '优惠券 - 均一价格详情',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(0, '单品打折'), (1, '满减打折'), (2, '均一价格')], default=1, verbose_name='优惠券类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitecoupon',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Coupon', verbose_name='优惠券'),
        ),
    ]
