# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20170615_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
    ]
