# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_order_food_food_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspec',
            name='vip_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5, verbose_name='会员价格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_image', to='user.Food', verbose_name='商品'),
        ),
    ]
