# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20170618_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='food',
            field=models.ManyToManyField(related_name='coupon_food', to='user.Food', verbose_name='打折商品'),
        ),
    ]
