# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20170619_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='订单编号'),
        ),
    ]
