# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_order_food_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '商品 - 过敏物质',
                'verbose_name_plural': '商品 - 过敏物质',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='热量'),
        ),
        migrations.AddField(
            model_name='order_food',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='food',
            name='allergens',
            field=models.ManyToManyField(to='user.Allergens', verbose_name='过敏物质'),
        ),
    ]
