# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20170625_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorder',
            name='code',
            field=models.CharField(default=1, max_length=50, verbose_name='订单编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
