# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0055_auto_20170625_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundorder',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
    ]
