# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_auto_20170625_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='stock',
        ),
    ]
