# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_auto_20170629_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_user',
            field=models.IntegerField(default=0, verbose_name='用餐人数'),
        ),
    ]
