# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_meal_total_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='code',
            field=models.CharField(max_length=30, verbose_name='支付编号'),
        ),
    ]
