# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_auto_20170708_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_vip_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='VIP总价'),
        ),
        migrations.AddField(
            model_name='order_food',
            name='vip_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='VIP价格'),
            preserve_default=False,
        ),
    ]
