# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20170708_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
    ]
