# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_auto_20170714_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullminuscoupon',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Food', verbose_name='赠品'),
        ),
    ]
