# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_auto_20170714_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='coupon_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_coupon', to='user.CouponCode', verbose_name='优惠券'),
        ),
    ]
