# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_auto_20170717_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
    ]
