# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_order_pay_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Coupon', verbose_name='优惠券'),
        ),
        migrations.AlterField(
            model_name='payinfo',
            name='coupon_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_coupon', to='user.CouponCode', verbose_name='优惠券代码'),
        ),
    ]
