# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_auto_20170819_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_vip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='VIP总价'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='不含税价格'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='不含税VIP价格'),
        ),
    ]
