# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_auto_20170819_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='basemob_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='环信UUID'),
        ),
    ]
