# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0091_auto_20170819_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='是否赠品分类'),
        ),
    ]
