# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0092_foodcategory_is_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FoodSpec', verbose_name='商品规格')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Stores', verbose_name='门店')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '赠品券',
                'verbose_name': '赠品券',
            },
        ),
    ]
