# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0094_auto_20170819_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='payinfo',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='税'),
        ),
    ]
