# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20170303_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileForm',
        ),
    ]
